<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>9.0</LangVersion>
    </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>GuestUnion.ObjectPool</AssemblyName>
    <RootNamespace>GuestUnion.ObjectPool</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
