<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <Authors>Xoderony</Authors>
    <Company>Xoderony</Company>
    <Copyright>Copyright (c) Xoderony</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Xoderony/Xoderony</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Xoderony/Xoderony.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>unity;upm;game;dotnet</PackageTags>
    <Version>0.1.0</Version>
    <InformationalVersion>0.1.0</InformationalVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
</Project>
