using System;
using System.Collections.Generic;
using System.Text;

namespace Xoderony.Localization.Tooling;

public static class StringTableKeyGenerator {

    private static readonly HashSet<string> ReservedKeywords = [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class",
        "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event",
        "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
        "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null",
        "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref",
        "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while"
    ];

    public static string Generate(IEnumerable<string> keys, string namespaceName, string typeName) {
        ArgumentNullException.ThrowIfNull(keys);
        ArgumentNullException.ThrowIfNull(namespaceName);
        ArgumentNullException.ThrowIfNull(typeName);

        ValidateNamespace(namespaceName);
        ValidateIdentifier(typeName, nameof(typeName));

        var root = new KeyNode(null);
        var keyCount = 0;
        foreach (var key in keys) {
            AddKey(root, key, nameof(keys));
            keyCount++;
        }

        if (keyCount == 0) {
            throw new ArgumentException("At least one localization key is required.", nameof(keys));
        }

        ValidateMemberNames(root, typeName, nameof(keys));

        var source = new StringBuilder();
        source.Append("// <auto-generated />\n\nnamespace ").Append(namespaceName).Append(";\n\n");
        source.Append("public static partial class ").Append(typeName).Append(" {\n");
        AppendMembers(source, root, 1);
        source.Append("}\n");
        return source.ToString();
    }

    private static void AddKey(KeyNode root, string key, string parameterName) {
        if (!IsValidKey(key)) {
            throw new ArgumentException($"'{key}' is not a valid localization key.", parameterName);
        }

        var current = root;
        var localKeys = key.Split('.');
        for (var index = 0; index < localKeys.Length; index++) {
            var localKey = localKeys[index];
            var identifier = ToPascalCase(localKey);
            if (current.Children.TryGetValue(identifier, out var child)) {
                if (!StringComparer.Ordinal.Equals(child.LocalKey, localKey)) {
                    throw new ArgumentException(
                        $"The local key '{localKey}' and '{child.LocalKey}' both generate the identifier '{identifier}'.",
                        parameterName);
                }
            } else {
                child = new KeyNode(localKey);
                current.Children.Add(identifier, child);
            }

            current = child;
            if (index < localKeys.Length - 1 && current.Key is not null) {
                throw new ArgumentException($"The key '{current.Key}' is also used as a key group.", parameterName);
            }
        }

        if (current.Children.Count != 0) {
            throw new ArgumentException($"The key '{key}' is also used as a key group.", parameterName);
        }

        if (current.Key is not null) {
            throw new ArgumentException($"The key '{key}' is duplicated.", parameterName);
        }

        current.Key = key;
    }

    private static void AppendMembers(StringBuilder source, KeyNode node, int depth) {
        foreach (var (identifier, child) in node.Children) {
            source.Append('\n').Append(' ', depth * 4);
            if (child.Key is not null) {
                source.Append("public const string ").Append(identifier).Append(" = \"").Append(child.Key).Append("\";\n");
                continue;
            }

            source.Append("public static class ").Append(identifier).Append(" {\n");
            AppendMembers(source, child, depth + 1);
            source.Append(' ', depth * 4).Append("}\n");
        }
    }

    private static bool IsValidKey(string? key) {
        if (string.IsNullOrEmpty(key)) {
            return false;
        }

        var segmentStart = true;
        var previousUnderscore = false;
        foreach (var character in key) {
            if (character == '.') {
                if (segmentStart || previousUnderscore) {
                    return false;
                }

                segmentStart = true;
                previousUnderscore = false;
                continue;
            }

            if (segmentStart) {
                if (character is < 'a' or > 'z') {
                    return false;
                }

                segmentStart = false;
                continue;
            }

            if (character == '_') {
                if (previousUnderscore) {
                    return false;
                }

                previousUnderscore = true;
                continue;
            }

            if (character is not (>= 'a' and <= 'z') and not (>= '0' and <= '9')) {
                return false;
            }

            previousUnderscore = false;
        }

        return !segmentStart && !previousUnderscore;
    }

    private static string ToPascalCase(string segment) {
        var identifier = new StringBuilder(segment.Length);
        var capitalize = true;
        foreach (var character in segment) {
            if (character == '_') {
                capitalize = true;
                continue;
            }

            identifier.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }

        return identifier.ToString();
    }

    private static void ValidateNamespace(string namespaceName) {
        if (namespaceName.Length == 0) {
            throw new ArgumentException("The namespace cannot be empty.", nameof(namespaceName));
        }

        foreach (var segment in namespaceName.Split('.')) {
            ValidateIdentifier(segment, nameof(namespaceName));
        }
    }

    private static void ValidateMemberNames(KeyNode node, string containingTypeName, string parameterName) {
        foreach (var (identifier, child) in node.Children) {
            if (StringComparer.Ordinal.Equals(identifier, containingTypeName)) {
                throw new ArgumentException(
                    $"The local key '{child.LocalKey}' generates the same identifier as its containing type '{containingTypeName}'.",
                    parameterName);
            }

            if (child.Key is null) {
                ValidateMemberNames(child, identifier, parameterName);
            }
        }
    }

    private static void ValidateIdentifier(string identifier, string parameterName) {
        if (identifier.Length == 0 || !IsIdentifierStart(identifier[0])) {
            throw new ArgumentException($"'{identifier}' is not a valid C# identifier.", parameterName);
        }

        for (var index = 1; index < identifier.Length; index++) {
            if (!IsIdentifierPart(identifier[index])) {
                throw new ArgumentException($"'{identifier}' is not a valid C# identifier.", parameterName);
            }
        }

        if (ReservedKeywords.Contains(identifier)) {
            throw new ArgumentException($"'{identifier}' is a reserved C# keyword.", parameterName);
        }
    }

    private static bool IsIdentifierStart(char character) {
        return character is '_' or (>= 'A' and <= 'Z') or (>= 'a' and <= 'z');
    }

    private static bool IsIdentifierPart(char character) {
        return IsIdentifierStart(character) || character is >= '0' and <= '9';
    }

    private sealed class KeyNode(string? localKey) {

        public string? LocalKey { get; } = localKey;

        public string? Key { get; set; }

        public SortedDictionary<string, KeyNode> Children { get; } = new(StringComparer.Ordinal);
    }
}
