<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
        <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>GuestUnion.UnityExtensions</AssemblyName>
    <RootNamespace>GuestUnion</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GenericExtensions\GenericExtensions.csproj" />
    <ProjectReference Include="..\Pool\ObjectPool.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\Unity 6000.0.24f1\Editor\Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
