using System;
using Xoderony.Localization.Tooling;
using Xunit;

namespace Xoderony.Localization.Tooling.Tests;

public sealed class StringTableKeyGeneratorTests {

    [Fact]
    public void GenerateCreatesNestedKeyTypes() {
        var source = StringTableKeyGenerator.Generate(
            ["main_menu.quit.message", "main_menu.start", "main_menu.quit.button"],
            "Example.Localization",
            "L10nKeys");

        const string expected = """
            // <auto-generated />

            namespace Example.Localization;

            public static partial class L10nKeys {

                public static class MainMenu {

                    public static class Quit {

                        public const string Button = "main_menu.quit.button";

                        public const string Message = "main_menu.quit.message";
                    }

                    public const string Start = "main_menu.start";
                }
            }

            """;

        Assert.Equal(expected, source);
    }

    [Fact]
    public void GenerateIsIndependentOfInputOrder() {
        var first = StringTableKeyGenerator.Generate(["menu.quit", "menu.start"], "Example", "Keys");
        var second = StringTableKeyGenerator.Generate(["menu.start", "menu.quit"], "Example", "Keys");

        Assert.Equal(first, second);
    }

    [Fact]
    public void GenerateRejectsDuplicateKeys() {
        Assert.Throws<ArgumentException>(() => StringTableKeyGenerator.Generate(["menu.start", "menu.start"], "Example", "Keys"));
    }

    [Theory]
    [InlineData("")]
    [InlineData(".menu")]
    [InlineData("menu.")]
    [InlineData("menu..start")]
    [InlineData("Main_menu")]
    [InlineData("main-menu")]
    [InlineData("1menu")]
    [InlineData("_menu")]
    [InlineData("menu_")]
    [InlineData("main__menu")]
    public void GenerateRejectsInvalidKeys(string key) {
        Assert.Throws<ArgumentException>(() => StringTableKeyGenerator.Generate([key], "Example", "Keys"));
    }

    [Fact]
    public void GenerateRejectsNormalizedIdentifierCollisions() {
        Assert.Throws<ArgumentException>(() => StringTableKeyGenerator.Generate(["item_2.name", "item2.name"], "Example", "Keys"));
    }

    [Theory]
    [InlineData("keys", "Keys")]
    [InlineData("menu.menu", "Keys")]
    public void GenerateRejectsMembersNamedAfterTheirContainingType(string key, string typeName) {
        Assert.Throws<ArgumentException>(() => StringTableKeyGenerator.Generate([key], "Example", typeName));
    }

    [Theory]
    [InlineData("menu", "menu.start")]
    [InlineData("menu.start", "menu")]
    public void GenerateRejectsLeafGroupConflicts(string first, string second) {
        Assert.Throws<ArgumentException>(() => StringTableKeyGenerator.Generate([first, second], "Example", "Keys"));
    }

    [Theory]
    [InlineData("")]
    [InlineData("Example.")]
    [InlineData("Example.Localization-Keys")]
    [InlineData("Example.class")]
    public void GenerateRejectsInvalidNamespaces(string namespaceName) {
        Assert.Throws<ArgumentException>(() => StringTableKeyGenerator.Generate(["menu.start"], namespaceName, "Keys"));
    }

    [Theory]
    [InlineData("")]
    [InlineData("1Keys")]
    [InlineData("Localization.Keys")]
    [InlineData("class")]
    public void GenerateRejectsInvalidTypeNames(string typeName) {
        Assert.Throws<ArgumentException>(() => StringTableKeyGenerator.Generate(["menu.start"], "Example", typeName));
    }

    [Fact]
    public void GenerateRejectsEmptyKeySequences() {
        Assert.Throws<ArgumentException>(() => StringTableKeyGenerator.Generate([], "Example", "Keys"));
    }
}
