<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\src\Xoderony.Serialization.Unity\Xoderony.Serialization.Unity.local.props" Condition="Exists('..\..\src\Xoderony.Serialization.Unity\Xoderony.Serialization.Unity.local.props')" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <ProjectReference Include="..\..\src\Xoderony.Serialization.Unity\Xoderony.Serialization.Unity.csproj" />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(UnityManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule" Condition="Exists('$(UnityManagedPath)\UnityEngine.SharedInternalsModule.dll')">
      <HintPath>$(UnityManagedPath)\UnityEngine.SharedInternalsModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
