<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyName>GuestUnion.GenericExtensions</AssemblyName>
    <RootNamespace>GuestUnion</RootNamespace>    
  </PropertyGroup>

</Project>
